spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/ground-hub
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100
        jdbc.batch_size: 100
        order_inserts: true
        order_updates: true
        batch_versioned_data: true
        jdbc.time_zone: UTC
        dialect: org.hibernate.dialect.MariaDBDialect